### ISSUE TITLE
Multiprocessing is broken

### ISSUE THREAD

**Issue by ADataGMan** [ASQLGman/state-law-analysis#1]
```
['http://www.gencourt.state.nh.us/rsa/html/nhtoc.htm']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\state-law-analysis\get-raw-data.py", line 87, in <module>
    p = pool.Pool(1)
  File "C:\Python3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Python3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Python3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by ADataGMan** [comment]
As part of using multiprocessing, the entry into the program needs to be specified, and it can be done with if __name__ == '__main__': . This appears to be done implicitly most of the time.
