### ISSUE TITLE
chunkedencodingerror

### ISSUE THREAD

**Issue by ADataGMan** [ASQLGman/state-law-analysis#2]
Figure out what this error is and then put something in place to handle it.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Python3\lib\site-packages\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Python3\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Python3\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Python3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\requests\models.py", line 749, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Python3\lib\site-packages\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Python3\lib\site-packages\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Python3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python3\lib\site-packages\urllib3\response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)", TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "e:\state-law-analysis\get-raw-data.py", line 40, in raw_retrieval
    raw_content = requests.get(request_url)
  File "C:\Python3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 662, in send
    r.content
  File "C:\Python3\lib\site-packages\requests\models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Python3\lib\site-packages\requests\models.py", line 752, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)", TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/state-law-analysis/get-raw-data.py", line 87, in <module>
    p.map(raw_retrieval, arl)
  File "C:\Python3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
requests.exceptions.ChunkedEncodingError: ("Connection broken: TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)", TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

**Comment by ADataGMan** [comment]
This error appeared to be part of the request that didn't succeed. Resolved this issue with exception handling, then set up retries with exponential backoff.
